services:
  # TEE Worker Client (existing service)
  worker:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    command: ["worker"]
    environment:
      - NODE_ENV=production
      - WORKER_URLS=${WORKER_URLS}
      - ALLOW_INSECURE_TLS=${ALLOW_INSECURE_TLS}
      - TWITTER_QUERIES=${TWITTER_QUERIES}
      - MAX_RESULTS=${MAX_RESULTS}
      - CADENCES=${CADENCES}
      - JOB_TYPE=${JOB_TYPE}
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

  # Masa AI Indexer (new service)
  indexer:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    command: ["indexer", "--continuous", "${DEFAULT_QUERY:-#AI}", "${DEFAULT_MAX_RESULTS:-100}"]
    volumes:
      - ./results:/app/results
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"